name: CVNubman
version: 1.18
api-version: 1.18
main: org.cubeville.cvnubman.CVNubman
description: Nubman minigame plugin
author: FrediW

commands:
  nubman:
    description: Set the current nubman player
    usage: /nubman
    permission: cvnubman.nubman
